name: webnetstat CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install deps
      run: sudo apt update && sudo apt install -y libpcap0.8 libpcap0.8-dev
    - name: install latest nim
      run: wget https://nim-lang.org/choosenim/init.sh && sudo sh init.sh -y
    - name: make
      run: make build_release
