name: webnetstat CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install deps
      run: sudo apt update && sudo apt install -y nim libpcap0.8 libpcap0.8-dev
    - name: make
      run: make build_release
